# This is a basic workflow to help you get started with Actions

name: Check Kotlin Convention & Unit Test

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the androidx branch
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Check code convention
      - name: Check code convention
        run: ./gradlew ktlint

      # Check build debug success
      - name: Build debug
        run: ./gradlew :app:assembleDevelopmentDebug

      # Run unit test
      - name: Run UT
        run: ./gradlew coverageReport

      # Upload coverage to codec
#      - name: Upload coverage report
#        run: bash <(curl -s --retry 10 https://codecov.io/bash) -f "presentation/build/reports/jacoco/fullCoverageReport/fullCoverageReport.xml"

      # Code coverage
      - uses: actions/checkout@master
      - uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          files: app/build/reports/jacoco/coverageReport/coverageReport.xml # optional
          flags: unittests # optional
          name: Pull quest coverage # optional
          fail_ci_if_error: true # optional (default = false)
          verbose: true # optional (default = false)
